name: Deploy Node.js App with Docker on EC2

on:
  push:
    branches: main
        # Triggers deployment when code is pushed to the main branch

jobs:
  build:

      # Ensures it runs on your EC2 self-hosted runner
     runs-on: self-hosted
     steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: login to docker hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD}} 
      - name: Ls console
        run: ls
      - name: Build Docker image
        
        run: |
         docker build -t "${{secrets.DOCKER_USERNAME}}"/prisma . 
      
   

      - name: Push docker image to docker hub  
        run: docker push "${{secrets.DOCKER_USERNAME}}"/prisma:latest 
        
  deploy:
     needs: build
     runs-on: [aws-ec2]
     steps:
      - name: Pull image from docker hub
        run: docker pull "${{secrets.DOCKER_USERNAME}}"/prisma:latest
      - name: Delete old container
        run: docker rm -f prisma-container || true
      - name: Run docker container   
        run: docker run -d --env-file .env -p $PORT:$PORT --name prisma-container "${{secrets.DOCKER_USERNAME}}"/prisma:latest
